config/routes.rb
Rails.application.routes.draw do
  
  resources :orders
  devise_for :users
  resources :photos

  resources :listings do
    resources :photos, :shallow => true
    resources :orders
  end

  resources :products do
    resources :listings
    resources :photos, :shallow => true
  end

  get 'pages/about'
  get 'pages/contact'
  get 'owner' => "listings#owner"
  get 'sales' => "orders#sales"
  get 'purchases' => "orders#purchases"

  root 'pages#index'

end

app/models/listing.rb
class Listing < ActiveRecord::Base

	belongs_to :product
	belongs_to :owner, class_name: "User"

	has_many :photos, :foreign_key => "listing_id", :dependent => :destroy

	has_many :orders

	accepts_nested_attributes_for :photos, :allow_destroy => true

	validates :name, :description, presence: true
	validates :rental_price_per_day, :rental_price_per_wk, :sale_price, numericality: { greater_than: 0 }

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:owner, :new, :create, :edit, :update, :destroy]
  before_filter :check_user, only: [:edit, :update, :destroy] # "check_user is a custom method defined below"

  def owner
    @listings = Listing.where(owner: current_user).order("created_at DESC")
  end

  # GET /listings
  # GET /listings.json
  def index
    if params[:product_id]
      @product = Product.find(params[:product_id])
      @listings = @product.listings
    else
      @listings = Listing.all.order("created_at DESC")
    end
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
    #@listing_images_array = @listing.images.split(/,\s*/)
    @listing = Listing.find(params[:id])
  end

  # GET /listings/new
  def new
    @listing = Listing.new
    # Split on comma with or without any whitespace (i.e. remove any whitespace between elements)
    #@listing_images_array = @listing.images.split(/,\s*/)
  end

  # GET /listings/1/edit
  def edit
    #@listing_images_array = @listing.images.split(/,\s*/)
    @listing = Listing.find(params[:id])
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)
    @listing.owner_id = current_user.id

    #@listing_images_array = @listing.images.split(/,\s*/)

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:name, :description, :mfr_date, :serial_no, :rental_price_per_day,
                                      :rental_price_per_wk, :security_deposit, :sale_price, :accept_offers,
                                      photos_attributes: [:id, :image, :caption, :_destroy])
    end

    # Check if current user is the listing owner before they're allowed to edit/update/destroy
    # (used in "before_filter" line at top of this file)
    def check_user
      if current_user != @listing.owner
        redirect_to listings_url, alert: "Sorry, this listing belongs to someone else"
      end
    end

end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%= nested_form_for @listing do |f| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h4>

      <ul>
      <% @listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :photos %><br>
    <div class="indented">
      <%= f.fields_for :photos do |photo_form| %>
        <%= photo_form.file_field :image %>
        Caption: <%= photo_form.text_area :caption %><br>
        <%= photo_form.link_to_remove "Remove this photo" %><br><br>
      <% end %>
    </div>
    <p><%= f.link_to_add "Add a photo", :photos %></p>
  </div>
    <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :mfr_date, 'Mfr. Year' %><br>
    <%= f.date_select :mfr_date, :discard_month => true, :start_year => Date.today.year, :end_year => 1850, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :serial_no, 'Serial No.' %><br>
    <%= f.text_field :serial_no, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :rental_price_per_day, "Rent/day" %><br>
    <%= f.text_field :rental_price_per_day, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :rental_price_per_wk, "Rent/wk" %><br>
    <%= f.text_field :rental_price_per_wk, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :security_deposit %><br>
    <%= f.text_field :security_deposit, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :sale_price %><br>
    <%= f.text_field :sale_price, class: "form-control" %>
  </div>
  <div class="checkbox">
    <label>
      <%= f.check_box :accept_offers %>
      Allow offers to buy this item
    </label>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form' %>

<%= link_to 'Show', @listing, class: "btn btn-link" %> |
<%= link_to 'Back', listings_path, class: "btn btn-link" %>

app/views/listings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <% if @listings.empty? %>
    No Listings Found
  <% else %>
    Listings
  <% end %>
  <% if @product %>
    <%= "for " + @product.brand_name + " " + @product.prod_name + ":" %>
  <% end %>
</h1>

<div class="row">
  <% @listings.each do |listing| %>
    <div class="col-md-3">
      <div class="thumbnail">
        <% photo = listing.photos.first || listing.photos.build %>
        <%= link_to image_tag(photo.image.url(:medium), alt: photo.caption), listing_path(listing) %><br>
        <div class="caption">
          <% listing_name = listing.name != "" ? listing.name : "No name" %>
          <h3><%= listing_name %></h3>
          <% owner_name = listing.owner != nil ? listing.owner.name : "UNKNOWN OWNER" %>
          <p><%= "Listed by #{owner_name}"%></p>
          <p>
            Mfr. date:        <%= listing.mfr_date %><br>
            Serial no.:       <%= listing.serial_no %><br>
            Price/day:        <%= listing.rental_price_per_day %><br>
            Price/wk:         <%= listing.rental_price_per_wk %><br>
            Security deposit: <%= listing.security_deposit %><br>
            For sale?
              <% if listing.accept_offers %>
                Yes
                <% if listing.sale_price %>
                  (<%= listing.sale_price %>)
                <% else %>
                  (no price set)
                <% end %>
              <% else %>
                No
              <% end %>
          </p>
        </div>

        <%= link_to 'Show', listing, class: "btn btn-link" %><br>
        <% if (user_signed_in?) && (current_user == listing.owner) %>
          <%= link_to 'Edit', edit_listing_path(listing), class: "btn btn-link" %><br>
          <%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<br>

<% if user_signed_in? %>
  <%= link_to 'New Listing', new_listing_path, class: "btn btn-link" %>
<% end %>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form' %>

<%= link_to 'Back', listings_path, class: "btn btn-link" %>

app/views/listings/owner.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <% if @listings.empty? %>
    Looks like you haven't posted any instruments yet.
    <%= link_to 'Create a listing now.', new_listing_path, class: "btn btn-link" %>
  <% else %>
    My Gear:
  <% end %>
</h1>

<table class="table table-striped table-bordered">
  <tr>
    <th class="center">Image</th>
    <th class="center">Name</th>
    <th class="center">Description</th>
    <th class="center">Daily Rental Price</th>
    <th class="center">Action</th>
  </tr>

  <% @listings.each do |listing| %>
    <tr>
      <td>
        <% if listing.photos.first %>
          <%= link_to (image_tag listing.photos.first.image.url(:thumb) || listing.photos.first.image.path(:thumb)), listing_path(listing) %>
        <% else %>
          <%= image_tag "no-image_thumb.png" %>
        <% end %>
      </td>
      <td><%= listing.name %></td>
      <td><%= listing.description %></td>
      <td><%= number_to_currency(listing.rental_price_per_day) %></td>
      <td>
        <div class="btn-group">
          <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
            Action <span class="caret"></span>
          </button>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "View", listing %></li>
            <li><%= link_to "Edit", edit_listing_path(listing) %></li>
            <li><%= link_to "Destroy", listing, method: :delete, data: { confirm: "Are you sure?" } %></li>
          </ul>
        </div>
      </td>
    </tr>
  <% end %>
</table>

<% if user_signed_in? %>
  <%= link_to 'New Listing', new_listing_path, class: "btn btn-link", data: { no_turbo_link: true } %>
<% end %>

app/views/listings/show.html.erb
<h1>"<%= @listing.name %>"</h1>
<h3>
  <strong><%= @listing.mfr_date.year.to_s + " " %>
  <% if @listing.product %>
    <%= link_to @listing.product.brand_name + " " + @listing.product.prod_name, @listing.product %></strong>
  <% end %>
</h3>

<p>
  <strong>Images:</strong><br>
    <% @listing.photos.each_with_index do |lp, num| %>
      <%= link_to image_tag(lp.image.url(:medium),  alt: "Image #{num}"), photo_path(lp) %>
    <% end %>
</p>

<p><strong>Description:</strong><%= @listing.description %></p>
<br /><div class="center"><%= link_to "Order Now", new_listing_order_path(@listing), class: "btn btn-primary", data: { no_turbo_link: true } %></div>
<p><strong>Serial no:</strong><%= @listing.serial_no %></p>
<p><strong>Rental price per day:</strong><%= number_to_currency(@listing.rental_price_per_day) %></p>
<p><strong>Rental price per wk:</strong><%= number_to_currency(@listing.rental_price_per_wk) %></p>
<p><strong>Security deposit:</strong><%= number_to_currency(@listing.security_deposit) %></p>
<p><strong>Sale price:</strong><%= number_to_currency(@listing.sale_price) %></p>
<p><strong>Accept offers:</strong><%= @listing.accept_offers %></p>

<% if current_user == @listing.owner %>
  <%= link_to 'Edit', edit_listing_path(@listing), class: "btn btn-link" %> |
<% end %>
<%= link_to 'Back', listings_path, class: "btn btn-link" %>