config/routes.rb
Rails.application.routes.draw do
  
  resources :orders
  devise_for :users
  resources :photos

  resources :listings do
    resources :photos, :shallow => true
    resources :orders
  end

  resources :products do
    resources :listings
    resources :photos, :shallow => true
  end

  get 'pages/about'
  get 'pages/contact'
  get 'owner' => "listings#owner"
  get 'sales' => "orders#sales"
  get 'purchases' => "orders#purchases"

  root 'pages#index'

end

app/models/photo.rb
class Photo < ActiveRecord::Base

	belongs_to :listing
	belongs_to :product

	has_attached_file :image,
		:styles => {
			:thumb => "100x100#",
			:medium => "400x400>",
			:large => "800x800>"
			},
		:path => ":style/:filename_:style",
		:default_url => "no-image_:style.png",
		:storage => :dropbox,
    	:dropbox_credentials => Rails.root.join("config/dropbox.yml")

  	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]

  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:image, :caption, :listing_id, :product_id, :image_size, :width, :height)
    end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.erb
<%= form_for(@photo) do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :image %><br>
    <%= image_tag @photo.image.url(:large) %>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :caption %><br>
    <%= f.text_area :caption, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing Photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Photos</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Caption</th>
      <th>Listing</th>
      <th>Product</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @photos.each do |photo| %>
      <tr>
        <td><%= link_to image_tag(photo.image.url(:thumb), alt: photo.caption), photo_path(photo) %></td>
        <td><%= photo.caption %></td>
        <td><%= photo.listing_id %></td>
        <td><%= photo.product_id %></td>
        <td><%= link_to 'Show', photo %></td>
        <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
        <td><%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Photo', new_photo_path %>

app/views/photos/new.html.erb
<h1>New Photo</h1>

<%= render 'form' %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<div class="center">
	<% if @photo.listing_id? %>
		<h2>Photo of <strong>"<%= @photo.listing.name %>"</strong> (<%= @photo.listing.product.brand_name %> <%= @photo.listing.product.prod_name %>):</h2>
	<% elsif %>
		<h2>Photo of <strong><%= @photo.product.brand_name %> <%= @photo.product.prod_name %></strong>:</h2>
	<% end %>
	<p>
	  <%= image_tag @photo.image.url(:large), alt: @photo.caption %>
	</p>

	<p>
	  <strong><%= @photo.caption %></strong>
	</p>

	<% if @photo.product_id? %>
		<%= link_to 'Edit', edit_photo_path %> |
		<%= link_to 'Back', product_path(@photo.product_id) %>
	<% elsif @photo.listing_id? %>
		<%= link_to 'Edit', edit_photo_path %>
		<%= link_to 'Back', listing_path(@photo.listing_id) %>
	<% end %>
</div>