config/routes.rb
Rails.application.routes.draw do
  
  resources :orders
  devise_for :users
  resources :photos

  resources :listings do
    resources :photos, :shallow => true
    resources :orders
  end

  resources :products do
    resources :listings
    resources :photos, :shallow => true
  end

  get 'pages/about'
  get 'pages/contact'
  get 'owner' => "listings#owner"
  get 'sales' => "orders#sales"
  get 'purchases' => "orders#purchases"

  root 'pages#index'

end

app/models/product.rb
class Product < ActiveRecord::Base

	has_many :listings
	has_many :photos, :foreign_key => "product_id", :dependent => :destroy

	accepts_nested_attributes_for :photos, :allow_destroy => true

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    @arranged_cards = arrange_product_cards(@products)
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def arrange_product_cards(products, arranged_cards=[])
      #cols_left_in_row = 4
      #landscape_cards_stacked_in_cell = 0
      #landscape_prods = []
      #portrait_prods = []
      width = 0
      height = 0
      
      products.each do |product|
        photo = product.photos.first || product.photos.build
        width, height = FastImage.size(photo.image.url(:medium)) || FastImage.size(photo.image.path(:medium))
        if width > height # First/cover image is landscape oriented
          # Push Landscape card into arranged_cards array
          arranged_cards << {:product => product, :photo => photo, :orientation => 'landscape'}
        else # If the card is in Portrait orientation
          # Push Portrait card into arranged_cards array
          arranged_cards << {:product => product, :photo => photo, :orientation => 'portrait'}
        end
      end

      return arranged_cards 
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:prod_type, :brand_name, :prod_name,
                                      photos_attributes: [:id, :image, :caption, :_destroy])
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_card_content.html.erb
<% if orientation == 'landscape' %>
  <div class="col-md-12">
<% elsif orientation == 'portrait' %>
  <div class="col-md-6">
<% end %>
    <%= link_to image_tag(photo.image.url(:medium), alt: photo.caption), product_path(product) %>
  </div>

<% if orientation == 'landscape' %>
  <div class="col-md-12">
<% elsif orientation == 'portrait' %>
  <div class="col-md-6">
<% end %>
    <div class="caption">
      <h3><%= link_to product.brand_name + " " + product.prod_name, product %></h3>
      <p>Type: <%= product.prod_type %></p><br>
      <%#= link_to 'About', product, class: "btn btn-link" %><!--<br>-->
      <%= link_to 'Listings ('+product.listings.count.to_s+')', product_listings_path(product), class: "btn btn-link" %><br>
      <%= link_to 'Edit', edit_product_path(product), class: "btn btn-link" %><br>
      <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %>
    </div>
  </div>

app/views/products/_form.html.erb
<%= nested_form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :photos %><br>
    <div class="indented">
      <%= f.fields_for :photos do |photo_form| %>
        <%= photo_form.file_field :image %>
        Caption: <%= photo_form.text_area :caption %><br>
        <%= photo_form.link_to_remove "Remove this photo" %><br><br>
      <% end %>
    </div>
    <p><%= f.link_to_add "Add a photo", :photos %></p>
  </div>
  <div class="field">
    <%= f.label :prod_type %><br>
    <%= f.text_field :prod_type %>
  </div>
  <div class="field">
    <%= f.label :brand_name %><br>
    <%= f.text_field :brand_name %>
  </div>
  <div class="field">
    <%= f.label :prod_name %><br>
    <%= f.text_field :prod_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<div class="row">
  <% @arranged_cards.each do |card| %>
      <div class="col-md-3">
        <div class="thumbnail row">
            <%= render 'products/card_content', :product => card[:product], :photo => card[:photo], :orientation => card[:orientation] %>
        </div>
      </div>
  <% end %>
</div>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @product.brand_name + " " + @product.prod_name %></h1>

<p>
  <strong>Images:</strong><br>
    <% @product.photos.each_with_index do |pp, num| %>
      <%= link_to image_tag(pp.image.url(:medium), 	alt: "Image #{num}"), photo_path(pp) %>
    <% end %>
</p>

<p>
  <strong>Type:</strong>
  <%= @product.prod_type %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @product.brand_name %>
</p>

<p>
  <strong>Model:</strong>
  <%= @product.prod_name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>
    <%= link_to 'See Listings ('+@product.listings.count.to_s+')', product_listings_path(@product) %>
  </strong>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>