config/routes.rb
Rails.application.routes.draw do
  
  resources :orders
  devise_for :users
  resources :photos

  resources :listings do
    resources :photos, :shallow => true
    resources :orders
  end

  resources :products do
    resources :listings
    resources :photos, :shallow => true
  end

  get 'pages/about'
  get 'pages/contact'
  get 'owner' => "listings#owner"
  get 'sales' => "orders#sales"
  get 'purchases' => "orders#purchases"

  root 'pages#index'

end

app/views/layouts/_copyright.html.erb
<div class="copyright">
	<div class="container">
		<h1 class="center">Hq</h1>
		<% if Date.today.year <= 2015 %>
			<p class="center">© 2015 Heroiq, Inc.</p>
		<% else %>
			<p class="center">© 2015-<%= Date.today.year %> Heroiq, Inc.</p>
		<% end %>
	</div>
</div>

app/views/layouts/_footer.html.erb
<div class="footer">
	<div class="container">
		<div class="col-md-2">
			<ul class="nav">
				<li><h4>LinkList 1</h4></li>
				<li><a href="#">Link 1</a></li>
				<li><a href="#">Link 2</a></li>
				<li><a href="#">Link 3</a></li>
				<li><a href="#">Link 4</a></li>
			</ul>
		</div>
		<div class="col-md-2">
			<ul class="nav">
				<li><h4>LinkList 2</h4></li>
				<li><a href="#">Link A</a></li>
				<li><a href="#">Link B</a></li>
				<li><a href="#">Link C</a></li>
				<li><a href="#">Link D</a></li>
			</ul>
		</div>
		<div class="col-md-2">
			<ul class="nav">
				<li><h4>LinkList 3</h4></li>
				<li><a href="#">Link 1a</a></li>
				<li><a href="#">Link 2b</a></li>
				<li><a href="#">Link 3c</a></li>
				<li><a href="#">Link 4d</a></li>
			</ul>
		</div>
		<div class="col-md-2">
			<ul class="nav">
				<li><h4>LinkList 4</h4></li>
				<li><a href="#">Link A1</a></li>
				<li><a href="#">Link B2</a></li>
				<li><a href="#">Link C3</a></li>
				<li><a href="#">Link D4</a></li>
			</ul>
		</div>
		<div class="col-md-2">
			<ul class="nav">
				<li><h4>Social/Sign up</h4></li>
				<li>
					FB TW PN QR LI
				</li>
				<li>Sign Up</li>
			</ul>
		</div>
	</div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">
        <%#= image_tag('heroiq-logo.png', size: '100x40')%>
        <!-- <span class="sr-only">heroiq</span></a> -->
        Heroiq
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "About", pages_about_path %></li>
        <li><%= link_to "Contact", pages_contact_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Browse Listings", listings_path %></li>
        <li><%= link_to "Discover Products", products_path %></li>

        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">My Gear<span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "Manage Listings", owner_path %></li>
              <li><%= link_to "Sales History", sales_path %></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
              <%= current_user.email %> <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "Order History", purchases_path %></li>
              <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Log In", new_user_session_path %></li>
        <% end %>

      </ul><!-- /.navbar-right -->
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_index.html.erb
<%= content_tag :div, class: ['jumbotron', 'jt-'+@imagenum.to_s] do %>
	<div class="container">
	<!--
		<p class="notice"><%= notice %></p>
       	<p class="alert"><%= alert %></p>
     -->
       	<% flash.each do |name, msg| %>
			<% if msg.is_a?(String) %>
				<div class="alert alert-<%= name.to_s == "notice" ? "success" : "danger" %> alert-dismissable">
					<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
					<%= content_tag :div, msg, :id => "flash_#{name}" %>
				</div>
			<% end %>
		<% end %>

		<div class="intro-area">
			<% if @left_biased_images.include?(@imagenum) %>
				<h1 class="col-md-4 left-biased-image">
			<% else %>
				<h1 class="col-md-4">
			<% end %>
					Local Guitars on Demand  <%# <------- Main tagline %>
				</h1>
		</div>
	</div>
<% end %>
<div class="content-wrapper">
	<div class="container">
		<%= yield %> <%# <----- Rest of HTML content defined in '/pages/index.html' %>
	</div>
</div> 

app/views/layouts/_page.html.erb
<div class="content-wrapper">
	<div class="container">
	<!--
		<p class="notice"><%= notice %></p>
       	<p class="alert"><%= alert %></p>
     -->
       	<% flash.each do |name, msg| %>
			<% if msg.is_a?(String) %>
				<div class="alert alert-<%= name.to_s == "notice" ? "success" : "danger" %> alert-dismissable">
					<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
					<%= content_tag :div, msg, :id => "flash_#{name}" %>
				</div>
			<% end %>
		<% end %>

		<%= yield %>

	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
	<title>Heroiq</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'https://js.stripe.com/v2/' %>
	<%= csrf_meta_tags %>
	<%= tag :meta, :name => "stripe-key", :content => ENV["STRIPE_PUBLISHABLE_KEY"] %>
</head>

<body>
	<%= render 'layouts/header' %>
	<% if current_page?(root_url) %>
		<%= render 'layouts/index' %>
	<% else %>
		<%= render 'layouts/page' %>
	<% end %>
	<%= render 'layouts/footer' %>
	<%= render 'layouts/copyright' %>
</body>

</html>